dataset:
  name: ODE_Lorenz
  pair_id: '1-9'  # Example: run on sub-datasets 1 to 3
model:
  name: Koopman
  # Observables parameters
  observables: "Polynomial" # Options: Identity, Polynomial, TimeDelay, RadialBasisFunctions, RandomFourierFeatures, ConcatObservables
  observables_cat_identity: False # Bool: Only called if observables is not Identity


  observables_poly_degree: 1 # Int: Only called if observables is Polynomial
  observables_time_delay: 1 # Int: Only called if observables is TimeDelay
  observables_rbf_centers_number: 100 # Int: Only called if observables is RadialBasisFunctions
  observables_rbf_kernel_width: 1.0 # Float: Only called if observables is RadialBasisFunctions
  observables_include_state: True # Bool: Only called if observables is RandomFourierFeatures
  observables_gamma: 1.0 # Float: Only called if observables is RandomFourierFeatures
  observables_D: 3 # Int: Only called if observables is RandomFourierFeatures

  
  # Regressor parameters
  regressor: "DMD" # Options: DMD, EDMD, HAVOK, KDMD, NNDMD
  regressor_dmd_rank: 10 # Int: Only called if regressor is DMD, EDMD, HAVOK, KDMD
  regressor_tlsq_rank: 10 # Int: Only called if regressor is EDMD, KDMD