dataset:
  name: ODE_Lorenz
  pair_id: '1-9'  # Example: run on sub-datasets 1 to 3
model:
  name: Koopman
  # Add Koopman model-specific parameters here
  dmd_rank: 10
  observables: "polynomial"
  observables_degree: 1