dataset:
  name: PDE_KS
  pair_id:
  - 8
model:
  name: Koopman
  observables: TimeDelay
  observables_cat_identity: true
  observables_float_param: 1.3639772810568866
  observables_include_state: true
  observables_int_param: 7
  observables_rbf_centers_number: 391
  regressor: EDMD
  regressor_dmd_rank: 48
  regressor_tlsq_rank: 93
  seed: 0
