dataset:
  name: PDE_KS
  pair_id: [1,2,3,4,5,6,7,8,9]
model:
  name: Koopman
  train_split: 0.75   # float in (0.7 and 1.0)
                     # proportion of train data to use for training
  seed: 0
  n_trials: 3
hyperparameters: # Specify hyperparameters and ranges
  # Observables parameters
  observables:
    type: choice
    choices: ["Polynomial"] # Options: Identity, Polynomial, TimeDelay, RadialBasisFunctions, RandomFourierFeatures, ConcatObservables
  observables_cat_identity:
    type: choice
    choices: [False] # Bool: Only called if observables is not Identity
  observables_int_param:
    type: choice
    choices: [1,2,3] # Int: Only called if observables is Polynomial
  observables_rbf_centers_number:
    type: choice
    choices: [100] # Int: Only called if observables is RadialBasisFunctions
  observables_float_param:
    type: choice
    choices: [1.0] # Float: Only called if observables is RadialBasisFunctions
  observables_include_state:
    type: choice
    choices: [True] # Bool: Only called if observables is RandomFourierFeatures
 
  # Regressor parameters
  regressor_dmd_rank:
    type: choice
    choices: [10] # Int: Only called if regressor is DMD, EDMD, HAVOK, KDMD
  regressor_tlsq_rank:
    type: choice
    choices: [10] # Int: Only called if regressor is EDMD, KDMD
  regressor:
    type: choice
    choices: ["DMD"] # Options: DMD, EDMD, HAVOK, KDMD, NNDMD
